# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.FilePathField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=False)),
            ],
        ),
    ]
