# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0003_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(max_length=500)),
                ('rating', models.SmallIntegerField()),
            ],
        ),
    ]
