# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='album',
            field=models.FilePathField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rating',
            name='artist',
            field=models.FilePathField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='genre',
            field=models.FilePathField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.FilePathField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
