# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0006_auto_20170419_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='album',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rating',
            name='artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rating',
            name='genre',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
