# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0007_auto_20170502_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='rating',
            name='album',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rating',
            name='artist',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rating',
            name='genre',
            field=models.CharField(default='unknown', max_length=256),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
