# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0008_auto_20170502_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='original',
            field=models.BooleanField(default=False),
        ),
    ]
