# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0009_rating_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
