# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0010_auto_20170512_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartPlaylistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemtype', models.PositiveSmallIntegerField(choices=[(0, 'empty'), (1, 'Rating greater or equal'), (2, 'Rating equal'), (3, 'Is in path'), (4, 'Genre'), (5, 'Artist'), (6, 'Year less or equal'), (7, 'Year greater or equal'), (8, 'Prevent intros')], default=0)),
                ('weight', models.FloatField(default=1.0)),
                ('payload', models.CharField(max_length=512)),
                ('negate', models.BooleanField(default=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piremote.SmartPlaylist')),
            ],
        ),
    ]
