# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0011_smartplaylist_smartplaylistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplaylistitem',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
