# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0013_auto_20170517_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPlaylistItemPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='smartplaylistitem',
            name='payload',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='smartplaylistitempayload',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piremote.SmartPlaylistItem'),
        ),
    ]
