# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0016_auto_20170519_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='path',
            field=models.FilePathField(db_index=True, max_length=500),
        ),
    ]
