# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0017_auto_20170620_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='album',
            field=models.CharField(db_index=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rating',
            name='artist',
            field=models.CharField(db_index=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='genre',
            field=models.CharField(db_index=True, default='unknown', max_length=256),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
