# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piremote', '0019_rating_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='time',
            new_name='length',
        ),
    ]
